=== lalessio/tecweb1/data/orari.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"

	elementFormDefault="qualified" >
	
		<xsd:element name="orari" type="Torari"/>
		
	<xsd:complexType name="Torari">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="orario" type="Torario"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Torario">
	<xsd:sequence maxOccurs="1">
	<xsd:element name="giorno" type="xsd:string"/>
	<xsd:element name="ora" type="xsd:time"/>
	</xsd:sequence>
	<xsd:attribute name="id" type="Tid" use="required"/>			
	</xsd:complexType>

	<xsd:simpleType name="Tid">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="999999"/>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== lalessio/tecweb1/data/orari.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<orari xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" orari.xsd">
	<giorno id="Lunedi">
		<ora>8:00-20:00</ora>
	</giorno>
	<giorno id="Martedi">
		<ora>10:00-23:00</ora>
	</giorno>
	<giorno id="Mercoledi">
		<ora>09:00 - 10:00</ora>
	</giorno>
	<giorno id="Giovedi">
		<ora>12:30 - 19:30</ora>
	</giorno>
	<giorno id="Venerdi">
		<ora>08:30 - 19:30</ora>
	</giorno>
	<giorno id="Sabato">
		<ora>08:00 - 21:00</ora>
	</giorno>
	<giorno id="Domenica">
		<ora>chiuso</ora>
	</giorno>
	<giorno id="Festivi">
		<ora>chiuso</ora>
	</giorno>
</orari>
<!-- Last Update by Luca 25/07/2016 -->
